/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puntoventa;

import com.toedter.calendar.JDateChooser;
import conexion.conex;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class pantallaEmbarque extends javax.swing.JFrame {

    /**
     * Creates new form pantallaEmbarque
     */
    DefaultTableModel tablaSolicitud, tablaEmbarque;

    public pantallaEmbarque() {
        tablaSolicitud = new DefaultTableModel();
        tablaSolicitud.setColumnIdentifiers(new Object[]{"Cajas de P.T.", "Piezas", "Clave de sector salud", "Clave colostomic", "Lote", "Descripcion"});

        tablaEmbarque = new DefaultTableModel();
        tablaEmbarque.setColumnIdentifiers(new Object[]{"Caja colectiva", "Piezas", "Pesos Dimensiones", "No. Guia"});

        initComponents();

        tablaSelecion.getColumnModel().getColumn(0).setMaxWidth(100);
        tablaSelecion.getColumnModel().getColumn(1).setMaxWidth(100);
        tablaSelecion.getColumnModel().getColumn(2).setMaxWidth(100);
        tablaSelecion.getColumnModel().getColumn(3).setMaxWidth(100);
        tablaSelecion.getColumnModel().getColumn(4).setMaxWidth(100);

        this.setLocationRelativeTo(null);
        this.setTitle("Guia de Embarque");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtClaveColos = new javax.swing.JTextField();
        txtClaveSalud = new javax.swing.JTextField();
        txtPiezasSoli = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        txtCaja = new javax.swing.JTextField();
        txtLote = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnAgregarSoli = new javax.swing.JButton();
        btnCancelarSoli = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaSelecion = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtDescripcionGeneral = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtPiezasEmbar = new javax.swing.JTextField();
        txtPesosDim = new javax.swing.JTextField();
        txtNumguia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCajaColectiva = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnCancelarEmbarque = new javax.swing.JButton();
        txtAgregarEmbarque = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        fechaEntrega = new com.toedter.calendar.JDateChooser();
        txtEntrego = new javax.swing.JTextField();
        txtAutorizo = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "seleccion", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        txtClaveColos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaveColosActionPerformed(evt);
            }
        });

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        txtCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCajaActionPerformed(evt);
            }
        });

        jLabel2.setText("Cajas de P.T:");

        jLabel8.setText("Descripcion:");

        jLabel5.setText("Clave Colostomic:");

        jLabel3.setText("piezas:");

        jLabel6.setText("Lote:");

        jLabel4.setText("Clave de sector salud:");

        btnAgregarSoli.setText("Agregar");
        btnAgregarSoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarSoliActionPerformed(evt);
            }
        });

        btnCancelarSoli.setText("Cancelar");
        btnCancelarSoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarSoliActionPerformed(evt);
            }
        });

        tablaSelecion.setModel(tablaSolicitud);
        jScrollPane4.setViewportView(tablaSelecion);

        txtDescripcionGeneral.setColumns(20);
        txtDescripcionGeneral.setRows(5);
        jScrollPane5.setViewportView(txtDescripcionGeneral);

        jLabel9.setText("Descripcion general:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPiezasSoli, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtClaveSalud, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtClaveColos, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAgregarSoli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtLote, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnCancelarSoli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 21, Short.MAX_VALUE))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtPiezasSoli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtClaveSalud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtClaveColos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnAgregarSoli)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelarSoli)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "2.- Embarque", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        txtNumguia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumguiaActionPerformed(evt);
            }
        });

        jLabel7.setText("Caja Colectiva:");

        txtCajaColectiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCajaColectivaActionPerformed(evt);
            }
        });

        jLabel12.setText("No. Guia");

        jLabel11.setText("Pesos Dimensiones:");

        jLabel10.setText("piezas:");

        btnCancelarEmbarque.setText("Cancelar");
        btnCancelarEmbarque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEmbarqueActionPerformed(evt);
            }
        });

        txtAgregarEmbarque.setText("Agregar");
        txtAgregarEmbarque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgregarEmbarqueActionPerformed(evt);
            }
        });

        jTable4.setModel(tablaEmbarque);
        jScrollPane6.setViewportView(jTable4);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(btnCancelarEmbarque)
                        .addGap(18, 18, 18)
                        .addComponent(txtAgregarEmbarque, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCajaColectiva, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPiezasEmbar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPesosDim, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumguia, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addComponent(jSeparator2)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCajaColectiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtPiezasEmbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtPesosDim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtNumguia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAgregarEmbarque)
                    .addComponent(btnCancelarEmbarque))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton5.setText("Cancelar");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ultimos Datos", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jLabel1.setText("Fecha de Entrega:");

        jLabel13.setText("Entregó:");

        jLabel14.setText("Autorizó:");

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Observaciones");

        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        jScrollPane7.setViewportView(txtObservaciones);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane7)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechaEntrega, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(2, 2, 2)
                        .addComponent(txtAutorizo))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEntrego)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(fechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtEntrego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtAutorizo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton6.setText("Registrar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarSoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarSoliActionPerformed
        agregarFilaTbSolicitud();
    }//GEN-LAST:event_btnAgregarSoliActionPerformed

    private void txtCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCajaActionPerformed

    private void txtClaveColosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaveColosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaveColosActionPerformed

    private void txtCajaColectivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCajaColectivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCajaColectivaActionPerformed

    private void txtNumguiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumguiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumguiaActionPerformed

    private void txtAgregarEmbarqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgregarEmbarqueActionPerformed
        agregarFilaTbEmbarque();
    }//GEN-LAST:event_txtAgregarEmbarqueActionPerformed

    private void btnCancelarEmbarqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEmbarqueActionPerformed
        cancelarEmbarque();
    }//GEN-LAST:event_btnCancelarEmbarqueActionPerformed

    private void btnCancelarSoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarSoliActionPerformed
        cancelarSolicitud();
    }//GEN-LAST:event_btnCancelarSoliActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantallaEmbarque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantallaEmbarque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantallaEmbarque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantallaEmbarque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pantallaEmbarque().setVisible(true);
            }
        });
    }
//**************************************************** metodos para la pantalla **********************

    public void agregarFilaTbSolicitud() {
        if (validarCampos(txtCaja)) {
            if (validarCampos(txtPiezasSoli)) {
                if (validarCampos(txtClaveSalud)) {
                    if (validarCampos(txtClaveColos)) {
                        if (validarCampos(txtLote)) {
                            if (validarCampos2(txtDescripcion)) {
                                tablaSolicitud.addRow(new Object[]{
                                    txtCaja.getText(),
                                    txtPiezasSoli.getText(),
                                    txtClaveSalud.getText(),
                                    txtClaveColos.getText(),
                                    txtLote.getText(),
                                    txtDescripcion.getText()});
                                cancelarSolicitud();
                            } else {

                            }
                        } else {

                        }
                    } else {

                    }
                } else {

                }
            } else {

            }
        } else {

        }
    }

    public void agregarFilaTbEmbarque() {
        if (validarCampos(txtCajaColectiva)) {
            if (validarCampos(txtPiezasEmbar)) {
                if (validarCampos(txtPesosDim)) {
                    if (validarCampos(txtNumguia)) {

                        tablaEmbarque.addRow(new Object[]{
                            txtCajaColectiva.getText(),
                            txtPiezasEmbar.getText(),
                            txtPesosDim.getText(),
                            txtNumguia.getText()});
                        cancelarEmbarque();
                    } else {

                    }

                } else {

                }
            } else {

            }
        } else {

        }
    }

    public void registrarEmbarque() {
        //validamos  que las tablas tengan minimo un registro
        if (tablaSolicitud.getRowCount() != 0) {
            if (tablaEmbarque.getRowCount() != 0) {
                if (fechaEntrega.getDate() != null) {
                    if (validarCampos(txtEntrego)) {
                        if (validarCampos(txtAutorizo)) {
                            //obtenemos los valores de la tabla y los demas campos:)
                            String descripcionGeneral = txtDescripcionGeneral.getText();
                            String fecha = obtenerFecha(fechaEntrega);
                            String entrego = txtEntrego.getText();
                            String autorizo = txtAutorizo.getText();
                            String observaciones = txtObservaciones.getText();
                            //registramos  los datos embarques
                            conex con2 = new conex();
                            Connection con=con2.getConnection();
                            String sql = "insert into embarques(autorizo,entrego,observaciones,descripcionGeneral,fechaEntrega,fechaRegistro,idCotizacion) values(?,?,?,?,NOW())";
                           
                            try {
                                //registramos en embarques
                                
                                
                                PreparedStatement ps = con.prepareStatement(sql);
                                ps.setString(1, autorizo);
                                ps.setString(2, entrego);
                                ps.setString(3, observaciones);
                                ps.setString(4, descripcionGeneral);
                                ps.setString(4, fecha);
                                
                                ps.executeUpdate();

                                //registramos la tablas solicitud en tb solicitud
                                for (int i = 0; i < tablaSelecion.getRowCount(); i++) {
                                    String cajasPT = tablaSelecion.getValueAt(i, 0) + "";
                                    String piezas = tablaSelecion.getValueAt(i, 0) + "";
                                    String claveSecto = tablaSelecion.getValueAt(i, 0) + "";
                                    String claveColo = tablaSelecion.getValueAt(i, 0) + "";
                                    String lote = tablaSelecion.getValueAt(i, 0) + "";
                                    String descripcion = tablaSelecion.getValueAt(i, 0) + "";
                                    //validamos cual tabla tiene  mas filas 
                                    String sql1 = "insert into solicitud (cajasPT,piezas,claveSalud,claveColostomic,lote,Descripcion,idEmbarques)";
                                    ps = con.prepareStatement(sql1);
                                    ps.executeUpdate();

                                }

                                for (int i = 0; i < tablaEmbarque.getRowCount(); i++) {
                                    String cajaColectiva = tablaEmbarque.getValueAt(i, 0) + "";
                                    String piezas = tablaEmbarque.getValueAt(i, 1) + "";
                                    String pesoDimensiones = tablaEmbarque.getValueAt(i, 2) + "";
                                    String numGuia = tablaEmbarque.getValueAt(i, 3) + "";
                                    String sql2="insert into embarque (cajaColectiva,piezas,pesoDimensiones,numGuia,idEmbarques) ";
                                     ps=con.prepareStatement(sql2);
                                     ps.executeUpdate();
                                }
                                
                                ps.close();
                                con.close();
                                con2.desconectar();

                            } catch (Exception e) {
                                System.out.println("error  al registar embarque " + e.getMessage());
                            }

                        }
                    }
                } else {
                    fechaEntrega.requestFocus();
                    JOptionPane.showMessageDialog(null, "Selecciona una fecha", "Advertencia", JOptionPane.WARNING_MESSAGE);
                }

            } else {
                JOptionPane.showMessageDialog(null, "No existe ningun registro en la tabla Embarque", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No existe ningun registro en la tabla Solictud", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }

    }

    public static String obtenerFecha(JDateChooser fecha) {
        int dia = fecha.getCalendar().get(Calendar.DAY_OF_MONTH);
        int mes = fecha.getCalendar().get(Calendar.MONTH) + 1;
        int año = fecha.getCalendar().get(Calendar.YEAR);
        String mes1 = mes + "";
        String dia1 = dia + "";
        if (dia <= 9) {
            dia1 = "0" + dia;
        }
        if (mes <= 9) {
            mes1 = "0" + mes;
        }

        //prueba
        String diaMesSeleccionado = "";
        try {
            String formato = fecha.getDateFormatString();
            java.util.Date date = fecha.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat(formato);
            String fechaDelDia = String.valueOf(sdf.format(date));
            diaMesSeleccionado = fechaDelDia.substring(0, 2);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Al menos elija una FECHA DE NACIMIENTO VALIDA ", "Error..!!", JOptionPane.ERROR_MESSAGE);

        }

        //String fechaDia = diaMesSeleccionado + "-" + mes1 + "-" + año;
        String fechaDia = año + "-" + mes1 + "-" + diaMesSeleccionado;

        return fechaDia;
    }

    public void cancelarSolicitud() {
        limpiarCampos(txtCaja);
        limpiarCampos(txtPiezasSoli);
        limpiarCampos(txtClaveSalud);
        limpiarCampos(txtClaveColos);
        limpiarCampos(txtLote);
        limpiarCampos(txtDescripcion);
    }

    public void cancelarEmbarque() {
        limpiarCampos(txtCajaColectiva);
        limpiarCampos(txtPiezasEmbar);
        limpiarCampos(txtPesosDim);
        limpiarCampos(txtNumguia);
    }

    public void limpiarCampos(JTextField texto) {
        texto.setText("");
    }

    public void limpiarCampos(JTextArea texto) {
        texto.setText("");
    }

    public boolean validarCampos(JTextField texto) {
        boolean ban = false;
        if (texto.getText().toString().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Completa el campo", "Advertencia!", JOptionPane.WARNING_MESSAGE);
            texto.requestFocus();
        } else {
            ban = true;
        }
        return ban;
    }

    public boolean validarCampos2(JTextArea texto) {
        boolean ban = false;
        if (texto.getText().toString().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Completa el campo", "Advertencia!", JOptionPane.WARNING_MESSAGE);
            texto.requestFocus();
        } else {
            ban = true;
        }
        return ban;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarSoli;
    private javax.swing.JButton btnCancelarEmbarque;
    private javax.swing.JButton btnCancelarSoli;
    private com.toedter.calendar.JDateChooser fechaEntrega;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable tablaSelecion;
    private javax.swing.JButton txtAgregarEmbarque;
    private javax.swing.JTextField txtAutorizo;
    private javax.swing.JTextField txtCaja;
    private javax.swing.JTextField txtCajaColectiva;
    private javax.swing.JTextField txtClaveColos;
    private javax.swing.JTextField txtClaveSalud;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextArea txtDescripcionGeneral;
    private javax.swing.JTextField txtEntrego;
    private javax.swing.JTextField txtLote;
    private javax.swing.JTextField txtNumguia;
    private javax.swing.JTextArea txtObservaciones;
    private javax.swing.JTextField txtPesosDim;
    private javax.swing.JTextField txtPiezasEmbar;
    private javax.swing.JTextField txtPiezasSoli;
    // End of variables declaration//GEN-END:variables
}
